global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "spring-actuator"
    metrics_path: ""/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ "inventory:8080", "order:8080" ]
