version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product
    ports:
      - "5432:5432"

  inventory:
    container_name: inventory
    image: inventory
    ports:
      - "8080:8080"
    restart: "always"